name: Deploy in beta
on: 
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh 2 commands using password
        uses: appleboy/ssh-action@master
        env:
          CLONE_DIR: "/home/john/node-grp2"
          REPO_URL: ${{ github.repository }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: CLONE_DIR,REPO_URL
          script: |
            echo "Hello world $CLONE_DIR"
            rm -rf $CLONE_DIR
            git clone -b develop git@github.com:$REPO_URL.git $CLONE_DIR
            cd $CLONE_DIR
            npm install
            npm run build
            cp .env.dist ./dist/.env
            cd dist && npm install
            sed -i 's/xenv/prod/g' .env
            sed -i 's/xport/${{ secrets.EXPRESS_PORT }}/g' .env
            npm install --production
            pm2 stop app-grp2
            pm2 start index.js --name "app-grp2"
            